### ISSUE TITLE
PA / RasterPropMonitor API request

### ISSUE THREAD

**Issue by MOARdV** [Crzyrndm/Pilot-Assistant#15]
I've had an outstanding request to expose Pilot Assistant capabilities in RasterPropMonitor.  I've looked at the PA source, and it looks like the methods I'd most likely need aren't all directly exposed.

It looks like I can query the PilotAssistant class to determine which control modes are enabled, and what mode they're in, so that part's easy.

What wasn't immediately obvious was how to query the current value (eg, if I determine VertActive == true && CurrentVerMode == VertMode.Altitude, how do I query the target hold altitude?).  It would be nice if I could call a method like GetCurrentVertSetPoint(VertMode.Altitude) and get a double in response.

The other API methods that would be nice are a method to disengage the pilots (unless setting the appropriate *Active Boolean directly is benign), and a method to engage a pilot / mode with a supplied set point (eg, SetVertPilot(VertMode.Altitude, 14000) ) that would enable the pilot, switch the mode, and set the altitude as requested.

I don't know how many of those changes are practical, so please let me know.

**Comment by Crzyrndm** [comment]
Engage/disengage and changing mode are handled through three functions (currently private, but I can change that in a few seconds since there's no real reason for it).

Heading: https://github.com/Crzyrndm/Pilot-Assistant/blob/master/PilotAssistant/FlightModules/PilotAssistant.cs#L394
Vertical: https://github.com/Crzyrndm/Pilot-Assistant/blob/master/PilotAssistant/FlightModules/PilotAssistant.cs#L442
Throttle: https://github.com/Crzyrndm/Pilot-Assistant/blob/master/PilotAssistant/FlightModules/PilotAssistant.cs#L532

They all use the common format: mode, active, [setTargetToCurrentValue = true]
If you're just activating a module or switching modes, you can call it directly. with the new mode and state.

Setting values is a bit of a mess right now, and getting values does look messy from an external perspective. I'll have a look at providing something a bit more accessible.

**Comment by Crzyrndm** [comment]
https://github.com/Crzyrndm/Pilot-Assistant/commit/278a03037648a3cf7c250b58c172698c8c699b65

Get/Set functions for each module. If you need anything else or there's a problem (I'm not actually using these yet, so...) just sing out

**Comment by MOARdV** [comment]
Awesome.  Those look good.  I'll give it a go later this evening once I get done with work.

**Comment by Crzyrndm** [comment]
A note on the set functions, setTarget should be true when you're sending it a value to use (target updating) and false if you just want to use the current flight condition (on/off, mode switches, etc.)

Also, can you use out variables with reflection? I figure the current mode would also be nice to get back with the setpoint

**Comment by MOARdV** [comment]
> Also, can you use ref/out variables with reflection?

I do get a ref or out variable from MechJeb using reflection - I'll have to double check the code to see which it was.  The mode values are public, IIRC, so I can ask them directly after calling the method, if nothing else.

**Comment by Crzyrndm** [comment]
Some updates from the previous 24 hours
* Pushed the pause toggle to a method (https://github.com/Crzyrndm/Pilot-Assistant/blob/master/PilotAssistant/FlightModules/PilotAssistant.cs#L717) that RPM can use
* Target updating now applied to GUI even if the modules are inactive (Still need to pass the value through again on activation if it's to be used)
* Fixed the speed control update not respecting the selected units. 
* Changing the speed reference (TAS/IAS/EAS) is handled by  the method ChangeSpeedRef (https://github.com/Crzyrndm/Pilot-Assistant/blob/09db59e63a4a5f15c8fb3679b266477fcff795ef/PilotAssistant/FlightModules/PilotAssistant.cs#L681)
* Changing the speed unit (m/s, km/h, etc.) can be handled through the method ChangeSpeedUnit (https://github.com/Crzyrndm/Pilot-Assistant/blob/master/PilotAssistant/FlightModules/PilotAssistant.cs#L711)
